// DuckTalesData.cs -- GENERATED by tools/mod/gen_ducktales.py; do not edit.
// References into Disney Crossy Road (the world-wide edition) that the player supplies
// as dcr.apk: mesh and sound GUIDs, names, scales. No game data is in here.
namespace DcrMod
{
    public static class DuckTalesData
    {
        public class F { public string Guid, Mat; public bool InSea; public F(string g, string m, bool s) { Guid = g; Mat = m; InSea = s; } }
        public class A { public string Name, Next; public float Speed; public F[] Frames; public A(string n, string x, float s, F[] f) { Name = n; Next = x; Speed = s; Frames = f; } }
        public class C
        {
            public string Id, Name, Anim, Prefab, Hop, GenericHop, Scream, FirstHop, Config;
            public float Scale, Zoom;
            public int IdleBehaviour;
            public bool RandomPitch;
            public A[] Select, Idle, Ready, Jump, AltJump, Dead, Blocked, Additional;
        }
        public static readonly C[] Chars = {
            new C {
                Id = "3100", Name = "Huey", Anim = "Ducktales_Huey", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpSmall", GenericHop = "Ducktales-JumpSmall", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3100	Huey	162	12	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_classic_figurine	DT-CS1-C	1000	1000	1000",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Huey-idle-1", "char-Ducktales_Huey-idle-1", 0.0f, new F[] { new F("11f68032f19c846d789e2f7e85b0df9d", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3101", Name = "Dewey", Anim = "Ducktales_Dewey", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpSmall", GenericHop = "Ducktales-JumpSmall", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3101	Dewey	163	12	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_classic_figurine	DT-CS1-C	1000	1000	1000",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Dewey-idle-1", "char-Ducktales_Dewey-idle-1", 0.0f, new F[] { new F("c325ac31e381e42aab91011cf6d1073f", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3102", Name = "Louie", Anim = "Ducktales_Louie", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpSmall", GenericHop = "Ducktales-JumpSmall", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3102	Louie	164	12	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_classic_figurine	DT-CS1-C	1000	1000	1000",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Louie-idle-1", "char-Ducktales_Louie-idle-1", 0.0f, new F[] { new F("4b0038e4be5804464aeecfd2b7d65077", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3103", Name = "Burger Beagle", Anim = "Ducktales_Burger", Prefab = "Ducktales Beagle Boys",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 1.0f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3103	Burger	167	12	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_classic_figurine	none	1000	1000	1000",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Burger-idle-1", "char-Ducktales_Burger-idle-1", 0.0f, new F[] { new F("7fffa6759dc5441d0864ed688fe8e2b8", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3104", Name = "Pixiu Chinese Dragon", Anim = "Ducktales_PixiuChineseDragon", Prefab = "Ducktales Pixiu",
                Hop = "Ducktales-JumpPixiu", GenericHop = "Ducktales-JumpPixiu", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3104	Pixiu Chinese Dragon	182	12	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_classic_figurine	DT-CS2-R	1000	1000	1000",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_PixiuChineseDragon-idle-1", "char-Ducktales_PixiuChineseDragon-idle-1", 0.0f, new F[] { new F("0836f6a8433d84f47875427f83e82564", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[] {
                new A("char-Ducktales_PixiuChineseDragon-jump-1", "char-Ducktales_PixiuChineseDragon-idle-1", 12.0f, new F[] { new F("5b8b05f5de4ae47318054b1d880d2c12", "VertexColourCharactersPixarCars", false), new F("38792772c01914bf5b80b2642e98bc9c", "VertexColourCharactersPixarCars", false), new F("935185cd1249543e0aaab5b1ef452e7f", "VertexColourCharactersPixarCars", false), new F("cadcfdb01a1d249d99aa62bc318049f8", "VertexColourCharactersPixarCars", false) }) },
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3105", Name = "Webbigail Vanderquack", Anim = "Ducktales_Webby", Prefab = "Ducktales Webby",
                Hop = "Ducktales-JumpSmall", GenericHop = "Ducktales-JumpSmall", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3105	Webby	165	12	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_rare_figurine	DT-CS1-C	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Webby-idle-1", "char-Ducktales_Webby-idle-1", 0.0f, new F[] { new F("4bda46ff50ca3487ea42015281aa2474", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[] {
                new A("char-Ducktales_Webby-jump-1", "char-Ducktales_Webby-idle-1", 0.0f, new F[] { new F("9d1e5c7aaef2d4ea5993b8a3735668fa", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_Webby-jump-2", "char-Ducktales_Webby-idle-1", 0.0f, new F[] { new F("533a3fd868e7c4a12ae39a5cd31a84f8", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_Webby-jump-3", "char-Ducktales_Webby-idle-1", 0.0f, new F[] { new F("eacaa5587650548759d1ef6a70ced788", "VertexColourCharactersPixarCars", false) }) },
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3106", Name = "Bouncer Beagle", Anim = "Ducktales_Bouncer", Prefab = "Ducktales Beagle Boys",
                Hop = "Ducktales-JumpLarge", GenericHop = "Ducktales-JumpLarge", Scream = "", FirstHop = "",
                Scale = 1.0f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3106	Bouncer	168	12	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_rare_figurine	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Bouncer-idle-1", "char-Ducktales_Bouncer-idle-1", 0.0f, new F[] { new F("5eb1c38be063c42d2b557998a4660825", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3107", Name = "Mrs. Beakley", Anim = "Ducktales_MrsBeakley", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.8500000238418579f, Zoom = 0.44999998807907104f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3107	Mrs Beakley	166	12	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_rare_figurine	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_MrsBeakley-idle-1", "char-Ducktales_MrsBeakley-idle-1", 5.0f, new F[] { new F("40d1305c10c2b4b59a885f20fe65e56b", "VertexColourCharactersPixarCars", true) }),
                new A("char-Ducktales_MrsBeakley-idle-2", "char-Ducktales_MrsBeakley-idle-2", 5.0f, new F[] { new F("eda3f7722ac394f949a2838d95ffc227", "VertexColourCharactersPixarCars", false), new F("eda3f7722ac394f949a2838d95ffc227", "VertexColourCharactersPixarCars", false), new F("c9e4addf9782e4b1a9d2f079449fdb30", "VertexColourCharactersPixarCars", false), new F("eda3f7722ac394f949a2838d95ffc227", "VertexColourCharactersPixarCars", false), new F("c9e4addf9782e4b1a9d2f079449fdb30", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_MrsBeakley-idle-3", "char-Ducktales_MrsBeakley-idle-3", 5.0f, new F[] { new F("eda3f7722ac394f949a2838d95ffc227", "VertexColourCharactersPixarCars", false), new F("eda3f7722ac394f949a2838d95ffc227", "VertexColourCharactersPixarCars", false), new F("c9e4addf9782e4b1a9d2f079449fdb30", "VertexColourCharactersPixarCars", false), new F("eda3f7722ac394f949a2838d95ffc227", "VertexColourCharactersPixarCars", false), new F("c9e4addf9782e4b1a9d2f079449fdb30", "VertexColourCharactersPixarCars", false), new F("c9e4addf9782e4b1a9d2f079449fdb30", "VertexColourCharactersPixarCars", false), new F("c9e4addf9782e4b1a9d2f079449fdb30", "VertexColourCharactersPixarCars", false), new F("eda3f7722ac394f949a2838d95ffc227", "VertexColourCharactersPixarCars", false), new F("c9e4addf9782e4b1a9d2f079449fdb30", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_MrsBeakley-idle-4", "char-Ducktales_MrsBeakley-idle-4", 5.0f, new F[] { new F("e0607c5d74bfa41f3b82ccccb26335ba", "VertexColourCharactersPixarCars", false), new F("813c79030d6b642438f26f295467081b", "VertexColourCharactersPixarCars", false), new F("e0607c5d74bfa41f3b82ccccb26335ba", "VertexColourCharactersPixarCars", false), new F("813c79030d6b642438f26f295467081b", "VertexColourCharactersPixarCars", false), new F("e0607c5d74bfa41f3b82ccccb26335ba", "VertexColourCharactersPixarCars", false), new F("813c79030d6b642438f26f295467081b", "VertexColourCharactersPixarCars", false), new F("9db1b571dc03b454f94c673017a1796e", "VertexColourCharactersPixarCars", false), new F("9db1b571dc03b454f94c673017a1796e", "VertexColourCharactersPixarCars", false), new F("9db1b571dc03b454f94c673017a1796e", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_MrsBeakley-idle-5", "char-Ducktales_MrsBeakley-idle-5", 5.0f, new F[] { new F("9db1b571dc03b454f94c673017a1796e", "VertexColourCharactersPixarCars", false), new F("9db1b571dc03b454f94c673017a1796e", "VertexColourCharactersPixarCars", false), new F("9db1b571dc03b454f94c673017a1796e", "VertexColourCharactersPixarCars", false), new F("813c79030d6b642438f26f295467081b", "VertexColourCharactersPixarCars", false), new F("e0607c5d74bfa41f3b82ccccb26335ba", "VertexColourCharactersPixarCars", false), new F("813c79030d6b642438f26f295467081b", "VertexColourCharactersPixarCars", false), new F("e0607c5d74bfa41f3b82ccccb26335ba", "VertexColourCharactersPixarCars", false), new F("813c79030d6b642438f26f295467081b", "VertexColourCharactersPixarCars", false), new F("e0607c5d74bfa41f3b82ccccb26335ba", "VertexColourCharactersPixarCars", false) }) },
                Ready = new A[0],
                Jump = new A[] {
                new A("char-Ducktales_MrsBeakley-jump-1", "char-Ducktales_MrsBeakley-idle-1", 5.0f, new F[] { new F("40d1305c10c2b4b59a885f20fe65e56b", "VertexColourCharactersPixarCars", true) }) },
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3108", Name = "Peghook's Ghost", Anim = "Ducktales_PeghooksGhost", Prefab = "Ducktales Peghooks Ghost",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3108	Peghook’s Ghost	184	12	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_rare_figurine	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_PeghooksGhost-idle-1", "char-Ducktales_PeghooksGhost-idle-1", 0.0f, new F[] { new F("4704cfaf9ca3342319cf0f71184f30fb", "VertexColourCharactersPixarCars", true) }),
                new A("char-Ducktales_PeghooksGhost-idle-2", "char-Ducktales_PeghooksGhost-idle-2", 5.0f, new F[] { new F("9e8df32cdd7e24161b886613ef6b8ed4", "VertexColourCharactersPixarCars", false), new F("5217be0f2250b437090a54b01af41f3c", "VertexColourCharactersPixarCars", false), new F("9e8df32cdd7e24161b886613ef6b8ed4", "VertexColourCharactersPixarCars", false), new F("5217be0f2250b437090a54b01af41f3c", "VertexColourCharactersPixarCars", false), new F("5217be0f2250b437090a54b01af41f3c", "VertexColourCharactersPixarCars", false), new F("5217be0f2250b437090a54b01af41f3c", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_PeghooksGhost-idle-3", "char-Ducktales_PeghooksGhost-idle-3", 6.0f, new F[] { new F("9e8df32cdd7e24161b886613ef6b8ed4", "VertexColourCharactersPixarCars", false), new F("5217be0f2250b437090a54b01af41f3c", "VertexColourCharactersPixarCars", false), new F("9e8df32cdd7e24161b886613ef6b8ed4", "VertexColourCharactersPixarCars", false), new F("5217be0f2250b437090a54b01af41f3c", "VertexColourCharactersPixarCars", false), new F("9e8df32cdd7e24161b886613ef6b8ed4", "VertexColourCharactersPixarCars", false), new F("5217be0f2250b437090a54b01af41f3c", "VertexColourCharactersPixarCars", false), new F("9e8df32cdd7e24161b886613ef6b8ed4", "VertexColourCharactersPixarCars", false) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3109", Name = "Donald Duck", Anim = "Ducktales_Donald", Prefab = "Ducktales Donald",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3109	Donald	161	12	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_epic_figurine	DT-CS1-C	166	166	142",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Donald-idle-1", "char-Ducktales_Donald-idle-1", 0.0f, new F[] { new F("2384302cafb584ebcaf5fc9cccb2d4a1", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[] {
                new A("char-Ducktales_Donald-blocked-1", "char-Ducktales_Donald-idle-1", 8.0f, new F[] { new F("0406172fcb74349568e6f227f97e6732", "VertexColourCharactersPixarCars", true), new F("8d45ea0bde76442bba822a89eb75f426", "VertexColourCharactersPixarCars", true), new F("0406172fcb74349568e6f227f97e6732", "VertexColourCharactersPixarCars", true), new F("8d45ea0bde76442bba822a89eb75f426", "VertexColourCharactersPixarCars", true), new F("0406172fcb74349568e6f227f97e6732", "VertexColourCharactersPixarCars", true), new F("8d45ea0bde76442bba822a89eb75f426", "VertexColourCharactersPixarCars", true) }) },
                Additional = new A[0],
            },
            new C {
                Id = "3110", Name = "Big Time Beagle", Anim = "Ducktales_BigTime", Prefab = "Ducktales Beagle Boys",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3110	Big Time	169	12	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_epic_figurine	none	166	166	142",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_BigTime-idle-1", "char-Ducktales_BigTime-idle-1", 0.0f, new F[] { new F("1e3499fbc63184db18c71b086ccf6ce4", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3111", Name = "Gyro", Anim = "Ducktales_Gyro", Prefab = "Ducktales Gyro",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.699999988079071f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3111	Gyro	173	12	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_epic_figurine	none	166	166	142",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Gyro-idle-1", "char-Ducktales_Gyro-idle-1", 0.0f, new F[] { new F("4bc29266f19364178ab07f8284623c60", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3112", Name = "Falcon Graves", Anim = "Ducktales_FalconGraves", Prefab = "Ducktales Falcon Graves",
                Hop = "Ducktales-JumpLarge", GenericHop = "Ducktales-JumpLarge", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3112	Falcon Graves	176	12	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	YES	NO	dcr_epic_figurine	none	166	166	142",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_FalconGraves-idle-1", "char-Ducktales_FalconGraves-idle-1", 0.0f, new F[] { new F("1b49af474609b4f038909fdea5b4169f", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[] {
                new A("char-Ducktales_FalconGraves_punch-1", "char-Ducktales_FalconGraves-idle-1", 8.0f, new F[] { new F("4014a7c0b516e457da27d385cf05a6b2", "VertexColourCharactersPixarCars", false) }) },
            },
            new C {
                Id = "3113", Name = "Scrooge McDuck", Anim = "Ducktales_Scrooge", Prefab = "Ducktales Scrooge",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3113	Scrooge	160	12	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Scrooge-idle-1", "char-Ducktales_Scrooge-idle-1", 0.0f, new F[] { new F("39f9c0c0461414cf3ae264b009b0dc4c", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3114", Name = "Launchpad McQuack", Anim = "Ducktales_Launchpad", Prefab = "Ducktales Launchpad",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3114	Launchpad	172	12	NO	YES	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Launchpad-idle-1", "char-Ducktales_Launchpad-idle-1", 0.0f, new F[] { new F("495ce9fab6fc24af7932dabbd54c1d19", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3115", Name = "Hack", Anim = "Ducktales_Hack", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.8500000238418579f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3115	Hack	177	12	NO	NO	NO	YES	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	YES	NO	dcr_rare_figurine	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Hack-idle-1", "char-Ducktales_Hack-idle-1", 0.0f, new F[] { new F("c42b155775c8342dba3c1d19890b7bd3", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3116", Name = "Slash", Anim = "Ducktales_Slash", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.8500000238418579f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3116	Slash	178	12	NO	NO	NO	YES	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	YES	NO	dcr_rare_figurine	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Slash-idle-1", "char-Ducktales_Slash-idle-1", 0.0f, new F[] { new F("fcf373a4ff5cb45a6b5fd2d635c88b35", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3117", Name = "Nik Nokturne", Anim = "Ducktales_NikNokturne", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.8500000238418579f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3117	Nik Nokturne	179	12	NO	NO	NO	YES	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	YES	NO	dcr_rare_figurine	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_NikNokturne-idle-1", "char-Ducktales_NikNokturne-idle-1", 5.0f, new F[] { new F("f8e1579400a1b4868a38b6d949ca7c05", "VertexColourCharactersPixarCars", true) }),
                new A("char-Ducktales_NikNokturne-idle-2", "char-Ducktales_NikNokturne-idle-2", 8.0f, new F[] { new F("f8e1579400a1b4868a38b6d949ca7c05", "VertexColourCharactersPixarCars", true), new F("153640701eb3a438d88c643c43e8ab65", "VertexColourCharactersPixarCars", false), new F("90bef5135977749b6927a887d4a9fb54", "VertexColourCharactersPixarCars", false), new F("8df9df40cb7b649a08390666efebc959", "VertexColourCharactersPixarCars", false), new F("416a37ba06718496b8ac77db7c96db83", "VertexColourCharactersPixarCars", false), new F("1e76f4e0af6324e28b29c9a2d7075f82", "VertexColourCharactersPixarCars", false), new F("1e76f4e0af6324e28b29c9a2d7075f82", "VertexColourCharactersPixarCars", false), new F("34c15ea739042466badb7cf783c17125", "VertexColourCharactersPixarCars", false), new F("2cd6d2e58baf440a098ba913cb2acfbc", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_NikNokturne-idle-3", "char-Ducktales_NikNokturne-idle-3", 10.0f, new F[] { new F("f8e1579400a1b4868a38b6d949ca7c05", "VertexColourCharactersPixarCars", true), new F("153640701eb3a438d88c643c43e8ab65", "VertexColourCharactersPixarCars", false), new F("90bef5135977749b6927a887d4a9fb54", "VertexColourCharactersPixarCars", false), new F("8df9df40cb7b649a08390666efebc959", "VertexColourCharactersPixarCars", false), new F("416a37ba06718496b8ac77db7c96db83", "VertexColourCharactersPixarCars", false), new F("1e76f4e0af6324e28b29c9a2d7075f82", "VertexColourCharactersPixarCars", false), new F("1e76f4e0af6324e28b29c9a2d7075f82", "VertexColourCharactersPixarCars", false), new F("34c15ea739042466badb7cf783c17125", "VertexColourCharactersPixarCars", false), new F("153640701eb3a438d88c643c43e8ab65", "VertexColourCharactersPixarCars", false), new F("90bef5135977749b6927a887d4a9fb54", "VertexColourCharactersPixarCars", false), new F("8df9df40cb7b649a08390666efebc959", "VertexColourCharactersPixarCars", false), new F("416a37ba06718496b8ac77db7c96db83", "VertexColourCharactersPixarCars", false), new F("1e76f4e0af6324e28b29c9a2d7075f82", "VertexColourCharactersPixarCars", false), new F("34c15ea739042466badb7cf783c17125", "VertexColourCharactersPixarCars", false), new F("153640701eb3a438d88c643c43e8ab65", "VertexColourCharactersPixarCars", false), new F("8df9df40cb7b649a08390666efebc959", "VertexColourCharactersPixarCars", false), new F("416a37ba06718496b8ac77db7c96db83", "VertexColourCharactersPixarCars", false), new F("1e76f4e0af6324e28b29c9a2d7075f82", "VertexColourCharactersPixarCars", false), new F("34c15ea739042466badb7cf783c17125", "VertexColourCharactersPixarCars", false), new F("153640701eb3a438d88c643c43e8ab65", "VertexColourCharactersPixarCars", false) }) },
                Ready = new A[0],
                Jump = new A[] {
                new A("char-Ducktales_NikNokturne-jump-1", "char-Ducktales_NikNokturne-idle-1", 1.0f, new F[] { new F("f8e1579400a1b4868a38b6d949ca7c05", "VertexColourCharactersPixarCars", true) }) },
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3118", Name = "Ma Beagle", Anim = "Ducktales_MaBeagle", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3118	Ma Beagle	170	12	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_MaBeagle-idle-1", "char-Ducktales_MaBeagle-idle-1", 0.0f, new F[] { new F("f31245468a5b246b9a30777af38ae9a1", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3119", Name = "Shadow Magica", Anim = "Ducktales_MagicaShadow", Prefab = "Ducktales MagicaShadow",
                Hop = "Ducktales-JumpMagica", GenericHop = "Ducktales-JumpMagica", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3119	Magica Shadow	181	12	NO	YES	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[] {
                new A("char-Ducktales_MagicaShadow-select-1", "char-Ducktales_MagicaShadow-select-1", 0.0f, new F[] { new F("7c1024764d6f34dd79ca9bfe2ccd3608", "VertexColourCharactersPixarCars", false) }) },
                Idle = new A[] {
                new A("char-Ducktales_MagicaShadow-idle-1", "char-Ducktales_MagicaShadow-idle-1", 0.0f, new F[] { new F("d1939128a7d6f42deaaf7b7fb0240b6d", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3120", Name = "Gizmoduck", Anim = "Ducktales_Gizmo", Prefab = "Ducktales Gizmo",
                Hop = "Common-EmptySound", GenericHop = "Common-EmptySound", Scream = "", FirstHop = "",
                Scale = 0.8999999761581421f, Zoom = 0.4000000059604645f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3120	Gizmo	171	12	NO	YES	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[] {
                new A("char-Ducktales_Gizmo-select-1", "char-Ducktales_Gizmo-select-1", 0.0f, new F[] { new F("fd44fb9c6414f49bfb4570fb60fe1575", "VertexColourCharactersPixarCars", true) }) },
                Idle = new A[] {
                new A("char-Ducktales_Gizmo-idle-1", "char-Ducktales_Gizmo-idle-1", 1.0f, new F[] { new F("22ce0bea5e196461d824f19c302aa0e5", "VertexColourCharactersPixarCars", false) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3121", Name = "Darkwing Duck", Anim = "Ducktales_DarkwingDuck", Prefab = "Ducktales Darkwing Duck",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3121	Darkwing Duck	175	12	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	dcr_epic_tickets_figurine	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_DarkwingDuck-idle-1", "char-Ducktales_DarkwingDuck-idle-1", 1.0f, new F[] { new F("5566dde76168946a49208a565864a758", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[] {
                new A("char-Ducktales_DarkwingDuck-jump-1", "char-Ducktales_DarkwingDuck-idle-1", 1.0f, new F[] { new F("5566dde76168946a49208a565864a758", "VertexColourCharactersPixarCars", true) }) },
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[] {
                new A("char-Ducktales_DarkwingDuck-hide-1", "char-Ducktales_DarkwingDuck-hidden-2", 5.0f, new F[] { new F("5566dde76168946a49208a565864a758", "VertexColourCharactersPixarCars", true), new F("9f0bd70c39adb4ca5a1bef60b2d42f3f", "VertexColourCharactersPixarCars", false), new F("8c9b018b7a60b4553aeefe1e99aff4fe", "VertexColourCharactersPixarCars", false), new F("76b06a3ae0b9b4e768618cfe27ed5373", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_DarkwingDuck-hidden-2", "char-Ducktales_DarkwingDuck-hidden-2", 0.0f, new F[] { new F("76b06a3ae0b9b4e768618cfe27ed5373", "VertexColourRandall", false) }) },
            },
            new C {
                Id = "3122", Name = "Pharaoh Toth-Ra", Anim = "Ducktales_PharaohTothRa", Prefab = "Ducktales Pharaoh Toth-Ra",
                Hop = "Ducktales-JumpLarge", GenericHop = "Ducktales-JumpLarge", Scream = "", FirstHop = "",
                Scale = 0.8500000238418579f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3122	Pharaoh Toth-Ra	185	12	NO	YES	NO	YES	NO	NO	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_PharaohTothRa-idle-1", "char-Ducktales_PharaohTothRa-idle-1", 0.0f, new F[] { new F("ee7b1667b248d4156960ad501c3d7578", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3123", Name = "Lena", Anim = "Ducktales_Lena", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpSmall", GenericHop = "Ducktales-JumpSmall", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3123	Lena	180	12	NO	NO	NO	YES	NO	NO	NO	NO	YES	NO	NO	NO	YES	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Lena-idle-1", "char-Ducktales_Lena-idle-1", 5.0f, new F[] { new F("78a912d1754504397badb77a7b725b18", "VertexColourCharactersPixarCars", true) }),
                new A("char-Ducktales_Lena-idle-2", "char-Ducktales_Lena-idle-2", 5.0f, new F[] { new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false), new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false), new F("40774aa5e57f445dc91eafeb69b70e14", "VertexColourCharactersPixarCars", false), new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false), new F("40774aa5e57f445dc91eafeb69b70e14", "VertexColourCharactersPixarCars", false), new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false), new F("40774aa5e57f445dc91eafeb69b70e14", "VertexColourCharactersPixarCars", false), new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false) }),
                new A("char-Ducktales_Lena-idle-3", "char-Ducktales_Lena-idle-3", 5.0f, new F[] { new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false), new F("40774aa5e57f445dc91eafeb69b70e14", "VertexColourCharactersPixarCars", false), new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false), new F("40774aa5e57f445dc91eafeb69b70e14", "VertexColourCharactersPixarCars", false), new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false), new F("40774aa5e57f445dc91eafeb69b70e14", "VertexColourCharactersPixarCars", false), new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false), new F("302fc32e4d49844fc848e9befe720b5c", "VertexColourCharactersPixarCars", false) }) },
                Ready = new A[0],
                Jump = new A[] {
                new A("char-Ducktales_Lena-jump-1", "char-Ducktales_Lena-idle-1", 5.0f, new F[] { new F("78a912d1754504397badb77a7b725b18", "VertexColourCharactersPixarCars", true) }) },
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
            new C {
                Id = "3124", Name = "Headless Man-Horse", Anim = "Ducktales_HeadlessHorseMan", Prefab = "Ducktales Headless Horse Man",
                Hop = "Ducktales-JumpLarge", GenericHop = "Ducktales-JumpLarge", Scream = "", FirstHop = "",
                Scale = 0.8999999761581421f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3124	Headless Horse Man	183	12	NO	NO	NO	NO	NO	NO	YES	NO	YES	NO	NO	NO	YES	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[] {
                new A("char-Ducktales_HeadlessHorseMan-select-1", "char-Ducktales_HeadlessHorseMan-select-1", 0.0f, new F[] { new F("4c566e7257b944598949495a60bd042a", "VertexColourCharactersPixarCars", false) }) },
                Idle = new A[] {
                new A("char-Ducktales_HeadlessHorseMan-idle-1", "char-Ducktales_HeadlessHorseMan-idle-1", 0.0f, new F[] { new F("a4867bb9057464704b78ea3fb35a643d", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[] {
                new A("char-Ducktales_HeadlessHorseMan-detached", "", 0.0f, new F[] { new F("ce131ab4a335944d29d52321158a245f", "VertexColourCharactersPixarCars", false) }) },
            },
            new C {
                Id = "3125", Name = "Flintheart Glomgold", Anim = "Ducktales_Glomgold", Prefab = "Ducktales PlayerController",
                Hop = "Ducktales-JumpNormal", GenericHop = "Ducktales-JumpNormal", Scream = "", FirstHop = "",
                Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0, RandomPitch = true,
                Config = "defineCharacter	3125	Glomgold	174	12	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	none	none	0	0	0",
                Select = new A[0],
                Idle = new A[] {
                new A("char-Ducktales_Glomgold-idle-1", "char-Ducktales_Glomgold-idle-1", 0.0f, new F[] { new F("0caa0c02e4a1542e2ba75fa94e100aa9", "VertexColourCharactersPixarCars", true) }) },
                Ready = new A[0],
                Jump = new A[0],
                AltJump = new A[0],
                Dead = new A[0],
                Blocked = new A[0],
                Additional = new A[0],
            },
        };
        public class S { public string Name; public int Sorting, Mixer; public string[] Guids; public S(string n, int s, int m, string[] g) { Name = n; Sorting = s; Mixer = m; Guids = g; } }
        // Mixer: 0 = the characters' group, 1 = the effects group (as in the SEA game's own mappings)
        public static readonly S[] Sounds = {
            new S("Ducktales-FalconGravesPunch", 115, 0, new[] { "66dcadd87605e024287e6eb51596cfb6" }),
            new S("Ducktales-DWDDisappear", 115, 0, new[] { "58f31e16bc69b4466be01bb3121c16f3" }),
            new S("Ducktales-HeliLoop", 115, 0, new[] { "0ce1eb41c800c4d63af114a0efcbc6e1", "66020dd4c9b314abd8275a83695de32e" }),
            new S("Ducktales-JumpHeli", 115, 0, new[] { "29d00d7b5b2a6465e887354febd4e1c1", "373cd488e1d0e440499da2ac1e094fb1", "20159986db5fc48a8aea9f3c77e2cc51" }),
            new S("Ducktales-JumpLarge", 115, 0, new[] { "1d3115e3c02ad4720a209646019203e6", "a90764521eeb740bf8ff42011659017d", "99e7e2c680653409292bdc980d1bab4e", "379edf391f5fb47a7bdd9cc36b13e5ad" }),
            new S("Ducktales-JumpMagica", 115, 0, new[] { "82890b818265d419cb811d14221a5246", "bee491eec851f4870b032243c371a2c9", "8332201ed29614e7f9bf15f50e539452" }),
            new S("Ducktales-JumpNormal", 115, 0, new[] { "56fdee507104d490484333c347e058ed", "5f39f4c78f5f840d2904b3eec8d81628", "b475e8bf0047048729911b2cdcb11315", "a5c1fbfe5f55a4eabbfe44c92c2f90dd", "b67595c13c0064991a546029a10201f9" }),
            new S("Ducktales-JumpScrooge", 115, 0, new[] { "ce583eb4c411f4fe3af728ddbac4032f", "9606dc5c32f3647bf89e5572e152e86c", "b76b6bd789a6c4114aeb11cffe2e1b49" }),
            new S("Ducktales-JumpPixiu", 115, 0, new[] { "7908e48990fe44bcaa020b655735fc50", "0da8a345c9ed645be8617f16d43b0afd", "bb02cb56d2067490293ab3756fd7ab3d", "3eb3542acd835484692057a91da7c303" }),
            new S("Ducktales-JumpSmall", 115, 0, new[] { "ebe13def4b7d7498ba92f58a825ab5e3", "eee1d69c522b744e395df48207977b0f", "4ad38b0e7b9d74b9b93115a7eb10a6f6", "32762ff261abc480c871412d3e905730" }),
            new S("Ducktales-MoneyPitHop", 115, 1, new[] { "e04d0a5f6ccb446cca12350fcde85b7c" }),
            new S("Ducktales-MoneyPitFast", 115, 1, new[] { "42c663dfd828541b1836511ccae7bf4a" }),
            new S("Ducktales-MoneyPitSlow", 115, 1, new[] { "157579754e97f41309a6dd9f6245222d" }),
        };
        // universe 115's own clips for mappings every universe has
        public static readonly string[][] Overrides = {
            new[] { "Common-EagleCall", "0f65c1a1a966d4ccd9261f3d875fdcfe" },
            new[] { "Common-EagleCallAlt", "9098aeaf869ba4369bf5ca2d2490609b" },
        };
    }
}
