// ExtrasData.cs -- GENERATED by tools/mod/gen_extras.py; do not edit.
// Figurines built from models already in the SEA game's own bundles: mesh GUIDs,
// names, scales and config lines (references only; no game data is in here).
using A = DcrMod.DuckTalesData.A;
using F = DcrMod.DuckTalesData.F;

namespace DcrMod
{
    public static class ExtrasData
    {
        public class X
        {
            public string Id, Template, Anim, Name, Hop, GenericHop, Config;
            public float Scale, Zoom;
            public int IdleBehaviour;
            public A[] Select, Idle, Jump;
        }
        public static readonly X[] Chars = {
            new X {
                Id = "3060", Template = "2100", Anim = "Aladdin_GoldenCamel", Name = "Golden Camel",
                Hop = null, GenericHop = null, Scale = 0.800000011920929f, Zoom = 0.20000000298023224f, IdleBehaviour = 0,
                Config = "defineCharacter	3060	Golden Camel	31	17	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-Aladdin_GoldenCamel-idle-1", "char-Aladdin_GoldenCamel-idle-1", 0.0f, new F[] { new F("1b6bed7a3ff754d42be41f048f3cb8cc", "VertexColourCharactersAladdin", true) }) },
                Jump = new A[0],
            },
            new X {
                Id = "3061", Template = "2100", Anim = "Aladdin_DragonGenie", Name = "Dragon Genie",
                Hop = null, GenericHop = null, Scale = 0.800000011920929f, Zoom = 0.20000000298023224f, IdleBehaviour = 0,
                Config = "defineCharacter	3061	Dragon Genie	32	17	NO	NO	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	42	42	35",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-Aladdin_DragonGenie-idle-1", "char-Aladdin_DragonGenie-idle-1", 0.0f, new F[] { new F("f375bb4a9101944c28770b76e17527a0", "VertexColourCharactersAladdin", true) }) },
                Jump = new A[] {
                    new A("char-Aladdin_DragonGenie-jump-1", "char-Aladdin_DragonGenie-idle-1", 6.0f, new F[] { new F("2af244d373fd84965b63184af506c676", "VertexColourCharactersAladdin", true) }),
                    new A("char-Aladdin_DragonGenie-jump-2", "char-Aladdin_DragonGenie-idle-1", 6.0f, new F[] { new F("f7e366f1da39848d9aa0ffd55bad4bef", "VertexColourCharactersAladdin", true) }) },
            },
            new X {
                Id = "2827", Template = "2801", Anim = "LiloAndStitch_WitchLilo", Name = "Witch Lilo",
                Hop = "LiloAndStitch-SmallHop", GenericHop = "LiloAndStitch-SmallHop", Scale = 0.800000011920929f, Zoom = 0.44999998807907104f, IdleBehaviour = 0,
                Config = "defineCharacter	2827	Witch Lilo	328	23	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-LiloAndStitch_WitchLilo-idle-1", "char-LiloAndStitch_WitchLilo-idle-1", 0.0f, new F[] { new F("385bb583035ed4dff9d7055d7368f273", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_WitchLilo-idle-2", "char-LiloAndStitch_WitchLilo-idle-2", 5.0f, new F[] { new F("385bb583035ed4dff9d7055d7368f273", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true), new F("cf153bc8f90454e9abf2d94b4669b46c", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true), new F("cf153bc8f90454e9abf2d94b4669b46c", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_WitchLilo-idle-3", "char-LiloAndStitch_WitchLilo-idle-3", 5.0f, new F[] { new F("385bb583035ed4dff9d7055d7368f273", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true), new F("cf153bc8f90454e9abf2d94b4669b46c", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true), new F("cf153bc8f90454e9abf2d94b4669b46c", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true), new F("cf153bc8f90454e9abf2d94b4669b46c", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true), new F("9b987fd11d4944389b3b1481f03f7487", "VertexColourCharacters", true) }) },
                Jump = new A[] {
                    new A("char-LiloAndStitch_WitchLilo-jump-1", "char-LiloAndStitch_WitchLilo-idle-1", 6.0f, new F[] { new F("68fc00439028d4678a77131306c260a5", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_WitchLilo-jump-2", "char-LiloAndStitch_WitchLilo-idle-1", 6.0f, new F[] { new F("70899734981d44fa7890da04155243d6", "VertexColourCharacters", true) }) },
            },
            new X {
                Id = "2825", Template = "2801", Anim = "LiloAndStitch_VampireStitch", Name = "Vampire Stitch",
                Hop = "LiloAndStitch-CapeHop", GenericHop = "LiloAndStitch-CapeHop", Scale = 0.800000011920929f, Zoom = 0.44999998807907104f, IdleBehaviour = 0,
                Config = "defineCharacter	2825	Vampire Stitch	335	23	NO	NO	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	42	42	35",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-LiloAndStitch_VampireStitch-idle-1", "char-LiloAndStitch_VampireStitch-idle-1", 0.0f, new F[] { new F("2da50c982ddb348419b923149c501dd2", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_VampireStitch-idle-2", "char-LiloAndStitch_VampireStitch-idle-2", 5.0f, new F[] { new F("2da50c982ddb348419b923149c501dd2", "VertexColourCharacters", true), new F("e3dfd4641ceb349cf87d56209658e4db", "VertexColourCharacters", true), new F("e3dfd4641ceb349cf87d56209658e4db", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("e3dfd4641ceb349cf87d56209658e4db", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("e3dfd4641ceb349cf87d56209658e4db", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_VampireStitch-idle-3", "char-LiloAndStitch_VampireStitch-idle-3", 5.0f, new F[] { new F("2da50c982ddb348419b923149c501dd2", "VertexColourCharacters", true), new F("e3dfd4641ceb349cf87d56209658e4db", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("e3dfd4641ceb349cf87d56209658e4db", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("e3dfd4641ceb349cf87d56209658e4db", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("e3dfd4641ceb349cf87d56209658e4db", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true), new F("1036b1ce5b20647daa5b4101174bebf6", "VertexColourCharacters", true) }) },
                Jump = new A[] {
                    new A("char-LiloAndStitch_VampireStitch-jump-1", "char-LiloAndStitch_VampireStitch-idle-1", 6.0f, new F[] { new F("8cbee58e886bd4bd99583af22b62b40e", "VertexColourCharacters", true) }) },
            },
            new X {
                Id = "2822", Template = "2801", Anim = "LiloAndStitch_ElfWendell", Name = "Elf Pleakley",
                Hop = null, GenericHop = null, Scale = 0.800000011920929f, Zoom = 0.44999998807907104f, IdleBehaviour = 0,
                Config = "defineCharacter	2822	Elf Pleakley	341	23	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-LiloAndStitch_ElfWendell-idle-1", "char-LiloAndStitch_ElfWendell-idle-1", 0.0f, new F[] { new F("32a59be97ec6244cc8fe8ed4233ac22a", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_ElfWendell-idle-2", "char-LiloAndStitch_ElfWendell-idle-2", 5.0f, new F[] { new F("32a59be97ec6244cc8fe8ed4233ac22a", "VertexColourCharacters", true), new F("178358bf179124e6c95ce534f6a45b2f", "VertexColourCharacters", true), new F("a9119fbbda19544eb8848bce3dda848f", "VertexColourCharacters", true), new F("178358bf179124e6c95ce534f6a45b2f", "VertexColourCharacters", true), new F("a9119fbbda19544eb8848bce3dda848f", "VertexColourCharacters", true), new F("a9119fbbda19544eb8848bce3dda848f", "VertexColourCharacters", true), new F("a9119fbbda19544eb8848bce3dda848f", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_ElfWendell-idle-3", "char-LiloAndStitch_ElfWendell-idle-3", 5.0f, new F[] { new F("32a59be97ec6244cc8fe8ed4233ac22a", "VertexColourCharacters", true), new F("178358bf179124e6c95ce534f6a45b2f", "VertexColourCharacters", true), new F("a9119fbbda19544eb8848bce3dda848f", "VertexColourCharacters", true), new F("178358bf179124e6c95ce534f6a45b2f", "VertexColourCharacters", true), new F("a9119fbbda19544eb8848bce3dda848f", "VertexColourCharacters", true), new F("178358bf179124e6c95ce534f6a45b2f", "VertexColourCharacters", true), new F("a9119fbbda19544eb8848bce3dda848f", "VertexColourCharacters", true), new F("178358bf179124e6c95ce534f6a45b2f", "VertexColourCharacters", true), new F("a9119fbbda19544eb8848bce3dda848f", "VertexColourCharacters", true) }) },
                Jump = new A[] {
                    new A("char-LiloAndStitch_ElfWendell-jump-1", "char-LiloAndStitch_ElfWendell-idle-1", 6.0f, new F[] { new F("df91af805679e4d97aa659a963694b5d", "VertexColourCharacters", true) }) },
            },
            new X {
                Id = "2823", Template = "2801", Anim = "LiloAndStitch_SantaJumba", Name = "Santa Jumba",
                Hop = "LiloAndStitch-HeavyHop", GenericHop = "LiloAndStitch-HeavyHop", Scale = 0.800000011920929f, Zoom = 0.3499999940395355f, IdleBehaviour = 0,
                Config = "defineCharacter	2823	Santa Jumba	345	23	NO	NO	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	42	42	35",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-LiloAndStitch_SantaJumba-idle-1", "char-LiloAndStitch_SantaJumba-idle-1", 0.0f, new F[] { new F("f68ddf32291eb41ba8c6dacae0aecc47", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_SantaJumba-idle-2", "char-LiloAndStitch_SantaJumba-idle-2", 5.0f, new F[] { new F("f68ddf32291eb41ba8c6dacae0aecc47", "VertexColourCharacters", true), new F("8f76514e948df4c3b883068dbc3a9a26", "VertexColourCharacters", true), new F("8f76514e948df4c3b883068dbc3a9a26", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_SantaJumba-idle-3", "char-LiloAndStitch_SantaJumba-idle-3", 5.0f, new F[] { new F("f68ddf32291eb41ba8c6dacae0aecc47", "VertexColourCharacters", true), new F("8f76514e948df4c3b883068dbc3a9a26", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true), new F("8f76514e948df4c3b883068dbc3a9a26", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true), new F("8f76514e948df4c3b883068dbc3a9a26", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true), new F("2f244c82659a04005928615372a89d20", "VertexColourCharacters", true) }) },
                Jump = new A[] {
                    new A("char-LiloAndStitch_SantaJumba-jump-1", "char-LiloAndStitch_SantaJumba-idle-1", 6.0f, new F[] { new F("9b76de27e7454435693621ff45ad2fd5", "VertexColourCharacters", true) }),
                    new A("char-LiloAndStitch_SantaJumba-jump-2", "char-LiloAndStitch_SantaJumba-idle-1", 6.0f, new F[] { new F("522d3821a7f8643b3a39c143c3245fd9", "VertexColourCharacters", true) }) },
            },
            new X {
                Id = "2320", Template = "2301", Anim = "Moana_TheOcean", Name = null,
                Hop = null, GenericHop = "Moana-WetHop", Scale = 0.800000011920929f, Zoom = 0.5f, IdleBehaviour = 0,
                Config = "defineCharacter	2320	The Ocean	402	19	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	42	42	35",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-Moana_TheOcean-idle-1", "char-Moana_TheOcean-idle-1", 0.0f, new F[] { new F("32c7dd80835a9413c928729905026cbf", "VertexColourCharactersMoanaOcean", true) }) },
                Jump = new A[0],
            },
            new X {
                Id = "801", Template = "937", Anim = "disney_friends_ClassicMickey", Name = null,
                Hop = null, GenericHop = null, Scale = 0.8f, Zoom = 0.7f, IdleBehaviour = 0,
                Config = "defineCharacter	801	Classic Mickey	117	2	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	1000	1000	1000",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-disney_friends_ClassicMickey-idle-1", "char-disney_friends_ClassicMickey-idle-1", 0.0f, new F[] { new F("aa74751d6d0764f9cb146bf4420a69cf", "VertexColourCharacters", true) }) },
                Jump = new A[0],
            },
            new X {
                Id = "861", Template = "937", Anim = "disney_friends_FantasiaBroom", Name = null,
                Hop = null, GenericHop = null, Scale = 0.8f, Zoom = 0.7f, IdleBehaviour = 2,
                Config = "defineCharacter	861	Broom	117	2	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	333	333	250",
                Select = new A[] {
                    new A("char-disney_friends_FantasiaBroom-select-1", "char-disney_friends_FantasiaBroom-select-1", 4.0f, new F[] { new F("2f2943bd3e6a94352ba0db4cb425fb39", "VertexColourCharacters", true), new F("315a41df0ec9648709519ec1fc4a7ee4", "VertexColourCharacters", true), new F("2f2943bd3e6a94352ba0db4cb425fb39", "VertexColourCharacters", true), new F("174bc42815cf9460eb769ffdd5b6cbb9", "VertexColourCharacters", true) }) },
                Idle = new A[] {
                    new A("char-disney_friends_FantasiaBroom-idle-1", "char-disney_friends_FantasiaBroom-idle-1", 0.0f, new F[] { new F("2f2943bd3e6a94352ba0db4cb425fb39", "VertexColourCharacters", true) }),
                    new A("char-disney_friends_FantasiaBroom-idle-2", "char-disney_friends_FantasiaBroom-idle-1", 4.0f, new F[] { new F("2f2943bd3e6a94352ba0db4cb425fb39", "VertexColourCharacters", true), new F("315a41df0ec9648709519ec1fc4a7ee4", "VertexColourCharacters", true), new F("2f2943bd3e6a94352ba0db4cb425fb39", "VertexColourCharacters", true), new F("174bc42815cf9460eb769ffdd5b6cbb9", "VertexColourCharacters", true), new F("2f2943bd3e6a94352ba0db4cb425fb39", "VertexColourCharacters", true), new F("315a41df0ec9648709519ec1fc4a7ee4", "VertexColourCharacters", true), new F("2f2943bd3e6a94352ba0db4cb425fb39", "VertexColourCharacters", true), new F("174bc42815cf9460eb769ffdd5b6cbb9", "VertexColourCharacters", true) }) },
                Jump = new A[] {
                    new A("char-disney_friends_FantasiaBroom-jump-1", "char-disney_friends_FantasiaBroom-idle-1", 6.0f, new F[] { new F("315a41df0ec9648709519ec1fc4a7ee4", "VertexColourCharacters", true) }),
                    new A("char-disney_friends_FantasiaBroom-jump-2", "char-disney_friends_FantasiaBroom-idle-1", 6.0f, new F[] { new F("174bc42815cf9460eb769ffdd5b6cbb9", "VertexColourCharacters", true) }) },
            },
            new X {
                Id = "803", Template = "937", Anim = "disney_friends_SafariMickey", Name = null,
                Hop = null, GenericHop = null, Scale = 0.8f, Zoom = 0.7f, IdleBehaviour = 2,
                Config = "defineCharacter	803	Safari Mickey	120	2	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	333	333	250",
                Select = new A[] {
                    new A("char-disney_friends_SafariMickey-select-1", "char-disney_friends_SafariMickey-select-1", 1.5f, new F[] { new F("b34d4b9ca1545433ca62b3993503c11d", "VertexColourCharacters", true), new F("2d3c51d157570433f88e414efb61d962", "VertexColourCharacters", true) }) },
                Idle = new A[] {
                    new A("char-disney_friends_SafariMickey-idle-1", "char-disney_friends_SafariMickey-idle-1", 0.0f, new F[] { new F("b34d4b9ca1545433ca62b3993503c11d", "VertexColourCharacters", true) }),
                    new A("char-disney_friends_SafariMickey-idle-2", "char-disney_friends_SafariMickey-idle-1", 3.0f, new F[] { new F("b34d4b9ca1545433ca62b3993503c11d", "VertexColourCharacters", true), new F("2d3c51d157570433f88e414efb61d962", "VertexColourCharacters", true), new F("2d3c51d157570433f88e414efb61d962", "VertexColourCharacters", true), new F("2d3c51d157570433f88e414efb61d962", "VertexColourCharacters", true), new F("b34d4b9ca1545433ca62b3993503c11d", "VertexColourCharacters", true) }) },
                Jump = new A[] {
                    new A("char-disney_friends_SafariMickey-jump-1", "char-disney_friends_SafariMickey-idle-1", 6.0f, new F[] { new F("2d3c51d157570433f88e414efb61d962", "VertexColourCharacters", true) }) },
            },
            new X {
                Id = "871", Template = "937", Anim = "disney_friends_Max", Name = null,
                Hop = null, GenericHop = null, Scale = 0.8f, Zoom = 0.7f, IdleBehaviour = 0,
                Config = "defineCharacter	871	Max	139	2	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	1000	1000	1000",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-disney_friends_Max-idle-1", "char-disney_friends_Max-idle-1", 0.0f, new F[] { new F("15461af4c474c4525b9ca3b6100a91fa", "VertexColourCharacters", true) }) },
                Jump = new A[0],
            },
            new X {
                Id = "860", Template = "937", Anim = "disney_friends_Oswald", Name = null,
                Hop = null, GenericHop = null, Scale = 0.8f, Zoom = 0.7f, IdleBehaviour = 0,
                Config = "defineCharacter	860	Oswald	159	2	NO	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	166	166	142",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-disney_friends_Oswald-idle-1", "char-disney_friends_Oswald-idle-1", 0.0f, new F[] { new F("359cb04d5ec5d4842829db7414658357", "VertexColourCharacters", true) }) },
                Jump = new A[0],
            },
            new X {
                Id = "869", Template = "937", Anim = "disney_friends_Ortensia", Name = null,
                Hop = null, GenericHop = null, Scale = 0.8f, Zoom = 0.7f, IdleBehaviour = 0,
                Config = "defineCharacter	869	Ortensia	159	2	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-disney_friends_Ortensia-idle-1", "char-disney_friends_Ortensia-idle-1", 0.0f, new F[] { new F("2ac3d929467284afba7a6ea7ba22b568", "VertexColourCharacters", true) }) },
                Jump = new A[0],
            },
            new X {
                Id = "1372", Template = "1376", Anim = "FindingDory_ScubaDiver", Name = null,
                Hop = null, GenericHop = null, Scale = 1.0f, Zoom = 0.35f, IdleBehaviour = 0,
                Config = "defineCharacter	1372	Scuba Diver	214	14	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-FindingDory_ScubaDiver-idle-1", "char-FindingDory_ScubaDiver-idle-1", 0.0f, new F[] { new F("7cb057c87db7f4dfa9480ff6665af199", "VertexColourCharacters", true) }) },
                Jump = new A[] {
                    new A("char-FindingDory_ScubaDiver-jump-1", "char-FindingDory_ScubaDiver-idle-1", 6.0f, new F[] { new F("a0d87ceb7a82e4085ab10f85416fc4e8", "VertexColourCharacters", true) }),
                    new A("char-FindingDory_ScubaDiver-jump-2", "char-FindingDory_ScubaDiver-idle-1", 6.0f, new F[] { new F("cfbe3ba1b233b4913a0864736d3d6331", "VertexColourCharacters", true) }) },
            },
            new X {
                Id = "2734", Template = "2733", Anim = "BeautyAndTheBeast_HumanCadenza", Name = "Human Cadenza",
                Hop = null, GenericHop = null, Scale = 0.8f, Zoom = 0.3f, IdleBehaviour = 0,
                Config = "defineCharacter	2734	Human Cadenza	87	22	NO	NO	NO	YES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	YES	NO	NO	none	none	333	333	250",
                Select = new A[0],
                Idle = new A[] {
                    new A("char-BeautyAndTheBeast_HumanCadenza-idle-1", "char-BeautyAndTheBeast_HumanCadenza-idle-1", 0.0f, new F[] { new F("8d863e001fcf745b2a40d050e7869339", "VertexColourCharacters", true) }) },
                Jump = new A[] {
                    new A("char-BeautyAndTheBeast_HumanCadenza-jump-1", "char-BeautyAndTheBeast_HumanCadenza-idle-1", 6.0f, new F[] { new F("04fa83c1d4e034d10ba8133c5be90f16", "VertexColourCharacters", true) }),
                    new A("char-BeautyAndTheBeast_HumanCadenza-jump-2", "char-BeautyAndTheBeast_HumanCadenza-idle-1", 6.0f, new F[] { new F("cc864e4ea77d54a8b91cee4c0422b896", "VertexColourCharacters", true) }) },
            },
        };
    }
}
