/* GENERATED by tools/offsets/derive_offsets.py -- do not hand-edit.
 *
 *   libunity.so  Unity 5.6.4f1 (Mono)  BuildID c576f3e34e800d75e8eff134fbb47fcdb423f38a
 *   libmono.so                              BuildID ?
 *
 * Disney Crossy Road is Unity 5.6/2017.4, which predate Swappy (2019.2), so
 * the frame pacer is the Choreographer VSYNC path -- pumped, not patched,
 * exactly as the Drive Ahead (2018.3) port does. The engine clock is
 * clock_gettime-backed and correct while awake; the Time hooks exist to
 * freeze it across sleep/HOME. Unlike Drive Ahead this is a Mono-JIT game,
 * so the GC offsets describe Mono bdwgc's tkill-based thread suspend.
 *
 * Every RVA carries the game's own leading words as a guard; consumers
 * verify before writing and SKIP on mismatch.
 */
#ifndef DCR_OFFSETS_H
#define DCR_OFFSETS_H
#include <stdint.h>

typedef struct { const char *name; uint32_t rva; uint32_t guard[4]; } DcrSite;
#define DCR_NSITES(a) ((int)(sizeof(a) / sizeof((a)[0])))

#define DCR_UNITY_BUILD_ID "c576f3e34e800d75e8eff134fbb47fcdb423f38a"
#define DCR_MONO_BUILD_ID  "?"

/* ===== TIME: 4 TimeManager entry points ===== */
#define DCR_RVA_GetTimeManager           0x02f22bcu
static const uint32_t DCR_GUARD_GetTimeManager[4] = { 0xe92d4800u, 0xe3a00007u, 0xebf8d908u, 0xe8bd8800u };
#define DCR_RVA_GetRealtimeSinceStartup  0x02f1d4cu
static const uint32_t DCR_GUARD_GetRealtimeSinceStartup[4] = { 0xe92d4010u, 0xe1a04000u, 0xeb0c60afu, 0xedd40b34u };
#define DCR_RVA_SetTimeScale             0x02f1cccu
static const uint32_t DCR_GUARD_SetTimeScale[4] = { 0xe92d4800u, 0xe24dd010u, 0xee001a10u, 0xed9f1a17u };
#define DCR_RVA_SetFixedDeltaTime        0x02f1bb0u
static const uint32_t DCR_GUARD_SetFixedDeltaTime[4] = { 0xed9f0a13u, 0xee011a10u, 0xeeb41ac0u, 0xeef1fa10u };

/* TimeManager field layout (Unity 5.6.4f1), read off the getters. */
#define DCR_TM_FIELD_FIXEDDELTA         0x38
#define DCR_TM_FIELD_MAXPARTICLEDELTA   0xec
#define DCR_TM_FIELD_TIMESCALE          0xe4
#define DCR_TM_FIELD_FRAMECOUNT         0xb4

/* ===== TIME: 11 Time icall bindings (of 23 declared) ===== */
static const DcrSite DCR_TIME_SITES[] = {
  { "get_time", 0x0a524d8u, { 0xe92d4800u, 0xebe27f76u, 0xedd00b20u, 0xeeb70be0u } },  /* field +0x80 OK */
  { "get_deltaTime", 0x0a52510u, { 0xe92d4800u, 0xebe27f68u, 0xe5900098u, 0xe8bd8800u } },  /* field +0x98 OK */
  { "get_unscaledTime", 0x0a52538u, { 0xe92d4800u, 0xebe27f5eu, 0xedd00b24u, 0xeeb70be0u } },  /* field +0x90 OK */
  { "get_unscaledDeltaTime", 0x0a52568u, { 0xe92d4800u, 0xebe27f52u, 0xe590009cu, 0xe8bd8800u } },  /* field +0x9c OK */
  { "get_fixedDeltaTime", 0x0a52588u, { 0xe92d4800u, 0xebe27f4au, 0xe5900038u, 0xe8bd8800u } },  /* field +0x38 OK */
  { "set_fixedDeltaTime", 0x0a52598u, { 0xe92d4010u, 0xe1a04000u, 0xebe27f45u, 0xe1a01004u } },  /* control-flow getter */
  { "get_maximumParticleDeltaTime", 0x0a525e8u, { 0xe92d4800u, 0xebe27f32u, 0xe59000ecu, 0xe8bd8800u } },  /* field +0xec OK */
  { "get_timeScale", 0x0a52610u, { 0xe92d4800u, 0xebe27f28u, 0xe59000e4u, 0xe8bd8800u } },  /* field +0xe4 OK */
  { "set_timeScale", 0x0a52620u, { 0xe92d4010u, 0xe1a04000u, 0xebe27f23u, 0xe1a01004u } },  /* control-flow getter */
  { "get_frameCount", 0x0a52638u, { 0xe92d4800u, 0xebe27f1eu, 0xe59000b4u, 0xe8bd8800u } },  /* field +0xb4 OK */
  { "get_realtimeSinceStartup", 0x0a52658u, { 0xe92d4800u, 0xebe27f16u, 0xebe27db9u, 0xec410b30u } },  /* control-flow getter */
};

/* ===== VSYNC ("swappy"): pumped, Choreographer patched to ret ===== */
#define DCR_RVA_WaitVSync          0x060a0e0u
static const uint32_t DCR_GUARD_WaitVSync[4] = { 0xe92d4070u, 0xe1a04000u, 0xe59f0058u, 0xe59f5058u };
#define DCR_VSYNC_MUTEX            0x12ec688u
#define DCR_VSYNC_COND             0x12ec68cu
#define DCR_VSYNC_COUNTER          0x12ec664u   /* int32 */
#define DCR_RVA_ChoreographerEnableVSync 0x060a53cu
static const uint32_t DCR_GUARD_ChoreographerEnableVSync[4] = { 0xe92d4830u, 0xe24dd010u, 0xebff602cu, 0xe3500010u };
#define DCR_RVA_ChoreographerStopVSync 0x060a668u
static const uint32_t DCR_GUARD_ChoreographerStopVSync[4] = { 0xe92d4830u, 0xe24dd010u, 0xebff5fe1u, 0xe3500010u };

/* ===== GC: Mono bdwgc tkill-based thread suspend (4 offsets) ===== */
#define DCR_MONO_THREAD_KILL       0x02bff68u   /* tkill wrapper */
#define DCR_MONO_GC_SUSPEND_FN         0x02bffd8u
#define DCR_MONO_GC_SUSPEND_SIG        30u
static const uint32_t DCR_GUARD_MONO_GC_SUSPEND[4] = { 0xe92d4810u, 0xe28db008u, 0xe24dd01cu, 0xe59f41b4u };
#define DCR_MONO_GC_RESTART_FN         0x02c0474u
#define DCR_MONO_GC_RESTART_SIG        24u
static const uint32_t DCR_GUARD_MONO_GC_RESTART[4] = { 0xe92d49f0u, 0xe28db018u, 0xe24dd01cu, 0xe59f61a4u };
#define DCR_MONO_GC_ACK_SEM_WAIT   0x0015f00u   /* restart ack sem_wait */

/* ===== MONO internals (libmono RVAs) ===== */
#define DCR_MONO_RVA_FlushIcache   0x010e844u   /* mono_arch_flush_icache: Linux cacheflush svc */
static const uint32_t DCR_MONO_GUARD_FlushIcache[4] = { 0xe92d0890u, 0xe28db008u, 0xe24dd014u, 0xe50b0018u };
#define DCR_MONO_RVA_SuspendHandler 0x02bfba8u  /* GC_suspend_handler (reference) */
static const uint32_t DCR_MONO_GUARD_SuspendHandler[4] = { 0xe92d4810u, 0xe28db008u, 0xe24dd01cu, 0xe50b0020u };
#define DCR_MONO_RVA_LookupThread  0x02be9b0u   /* GC_lookup_thread(pthread_t) */
static const uint32_t DCR_MONO_GUARD_LookupThread[4] = { 0xe92d4810u, 0xe28db008u, 0xe24dd014u, 0xe50b0018u };
#define DCR_MONO_GOT_StopCount     0x0395bd4u   /* GOT slot -> &GC_stop_count */
#define DCR_MONO_GOT_AckSem        0x0395bdcu   /* GOT slot -> &GC_suspend_ack_sem */
#define DCR_MONO_GCT_SIGNAL     0xc   /* GC_thread->stop_info field */
#define DCR_MONO_GCT_LAST_STOP  0x10   /* GC_thread->stop_info field */
#define DCR_MONO_GCT_STACK_PTR  0x14   /* GC_thread->stop_info field */

#endif /* DCR_OFFSETS_H */
